<?php

namespace App\Model;

class TaxonsResource
{
    public function __construct(
        public int $id,
        public int $referenceId,
        public ?int $parentId,
        public string $scientificName,
        public string $authority,
        public string $fullName,
        public string $fullNameHtml,
        public string $rankId,
        public string $rankName,
        public string $referenceName,
        public string $referenceNameHtml,
        public string $frenchVernacularName,
        public string $englishVernacularName,
        public string $genusName,
        public string $familyName,
        public string $orderName,
        public string $className,
        public string $phylumName,
        public string $kingdomName,
        public ?string $vernacularGenusName,
        public ?string $vernacularFamilyName,
        public ?string $vernacularOrderName,
        public ?string $vernacularClassName,
        public ?string $vernacularPhylumName,
        public ?string $vernacularKingdomName,
        public ?string $vernacularGroup1,
        public ?string $vernacularGroup2,
        public ?string $vernacularGroup3,
        public ?string $habitat,
        public ?string $fr,
        public ?string $gf,
        public ?string $mar,
        public ?string $gua,
        public ?string $sm,
        public ?string $sb,
        public ?string $spm,
        public ?string $may,
        public ?string $epa,
        public ?string $reu,
        public ?string $sa,
        public ?string $ta,
        public ?string $nc,
        public ?string $wf,
        public ?string $pf,
        public ?string $cli,
        public string $taxrefVersion,
        public ?array $links,
    ) { }

    public static function from(array $data): TaxonsResource
    {
        return new TaxonsResource(
            $data["id"],
            $data["referenceId"],
            $data["parentId"] ?? null,
            $data["scientificName"],
            $data["authority"],
            $data["fullName"],
            $data["fullNameHtml"],
            $data["rankId"],
            $data["rankName"],
            $data["referenceName"],
            $data["referenceNameHtml"],
            $data["frenchVernacularName"],
            $data["englishVernacularName"],
            $data["genusName"],
            $data["familyName"],
            $data["orderName"],
            $data["className"],
            $data["phylumName"],
            $data["kingdomName"],
            $data["vernacularGenusName"] ?? null,
            $data["vernacularFamilyName"] ?? null,
            $data["vernacularOrderName"] ?? null,
            $data["vernacularClassName"] ?? null,
            $data["vernacularPhylumName"] ?? null,
            $data["vernacularKingdomName"] ?? null,
            $data["vernacularGroup1"] ?? null,
            $data["vernacularGroup2"] ?? null,
            $data["vernacularGroup3"] ?? null,
            $data["habitat"] ?? null,
            $data["fr"] ?? null,
            $data["gf"] ?? null,
            $data["mar"] ?? null,
            $data["gua"] ?? null,
            $data["sm"] ?? null,
            $data["sb"] ?? null,
            $data["spm"] ?? null,
            $data["may"] ?? null,
            $data["epa"] ?? null,
            $data["reu"] ?? null,
            $data["sa"] ?? null,
            $data["ta"] ?? null,
            $data["nc"] ?? null,
            $data["wf"] ?? null,
            $data["pf"] ?? null,
            $data["cli"] ?? null,
            $data["taxrefVersion"],
            isset($data["_links"]) ? array_map(fn(array $linkData) => Link::from($linkData), $data['_links']) : null,
        );
    }
}
